site_name: Terraform modules

copyright: Bogomil Petkuchev

theme:
  name: material
  #custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  palette:
    primary: black
  font:
    text: Nunito
    code: Nunito Mono
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - AWS:
    - Elasticache: redis.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      type: date
  - section-index
  - render_swagger

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bopetkuchev/

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/mermaid/dist/mermaid.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
